<template>
  <q-form>
    <q-list>
      <q-item v-for="item in transport_types" :key="item['position']" tag="li">
        <q-item-section>
          <q-img :src="item['image_url']" style="height: auto; max-width: 150px"/>
          <q-item-label>{{ item['title_en_us'] }}</q-item-label>
        </q-item-section>
      </q-item>
    </q-list>
    <q-select
      v-model="setCurrency"
      v-for="curr in currencies"
      :key="curr['id']"
      :options="curr['code']"
      behavior="menu"
      label="12345"
    />
    <q-select
      v-model="setLanguage"
      v-for="lang in languages"
      :key="lang['id']"
      :options="lang['lang_code']"
      behavior="menu"
      label="54321"
    />
    <q-btn flat dense round icon="check_circle" @click="acceptLang" aria-label="save"/>
  </q-form>
</template>

<script>
export default {
  name: 'TestPanel',
  data() {
    return {
      transport_types: [
        {
          id: 1,
          title_en_us: 'Passenger car',
          position: 1,
          enabled: true,
          title_ru_ru: 'Легковой автомобиль',
          title_de_de: 'Personenkraftwagen',
          title_fr_fr: 'Voiture de tourisme',
          title_it_it: 'Autovettura',
          title_es_es: 'Vagón de pasajeros',
          title_pt_pt: 'Automovel',
          title_nl_nl: 'Personenauto',
          title_zh_cn: '乘用车',
          title_el_gr: 'Επιβατικό αυτοκίνητο',
          title_hi_in: 'यात्री कार',
          title_tr_tr: 'Bin carek otomobil',
          image_url:
            'https://gettransport.com/uploads/store/9279951e9f23a3b2685d84d8c696b90f.png'
        },
        {
          id: 2,
          title_en_us: 'Minivan',
          position: 2,
          enabled: true,
          title_ru_ru: 'Каблук',
          title_de_de: 'Minivan',
          title_fr_fr: 'Camionnette',
          title_it_it: 'Monovolume',
          title_es_es: 'Monovolumen',
          title_pt_pt: 'Vagonete',
          title_nl_nl: 'Minibus',
          title_zh_cn: '面包车',
          title_el_gr: 'Μίνιβαν',
          title_hi_in: 'Minivan',
          title_tr_tr: 'Minivan',
          image_url:
            'https://gettransport.com/uploads/store/25531787b11fe963612f1bc3e0c456ff.png'
        },
        {
          id: 3,
          title_en_us: 'Porter',
          position: 3,
          enabled: true,
          title_ru_ru: 'Портер',
          title_de_de: 'Portier',
          title_fr_fr: 'Bagagiste',
          title_it_it: 'Porter',
          title_es_es: 'Porter',
          title_pt_pt: 'Porteiro',
          title_nl_nl: 'Porter',
          title_zh_cn: '波特',
          title_el_gr: 'Αχθοφόρος',
          title_hi_in: 'पोर्टर',
          title_tr_tr: 'Kapıcı',
          image_url:
            'https://gettransport.com/uploads/store/f823b17c12a8c8975d72cb3bb4c65184.png'
        },
        {
          id: 4,
          title_en_us: 'Transit',
          position: 4,
          enabled: true,
          title_ru_ru: 'Газель',
          title_de_de: 'Transit',
          title_fr_fr: 'Transit',
          title_it_it: 'Furgone',
          title_es_es: 'Сamioneta',
          title_pt_pt: 'Transporte',
          title_nl_nl: 'Doorvoer',
          title_zh_cn: '过境',
          title_el_gr: 'Διέλευση',
          title_hi_in: 'पारगमन',
          title_tr_tr: 'Transit',
          image_url:
            'https://gettransport.com/uploads/store/b339ec71cb6f08eb6a3c133ce37ee389.png'
        },
        {
          id: 5,
          title_en_us: '5-ton truck',
          position: 5,
          enabled: true,
          title_ru_ru: '5-тонный грузовик',
          title_de_de: '5-Tonne',
          title_fr_fr: 'Camion de 5 tonnes',
          title_it_it: 'Camion da 5 tonnellate',
          title_es_es: 'Camión de 5 toneladas',
          title_pt_pt: '5 toneladas',
          title_nl_nl: 'Vrachtwagen van 5 ton',
          title_zh_cn: '5吨卡车',
          title_el_gr: '5 τόνων',
          title_hi_in: '5 टन ट्रक',
          title_tr_tr: '5 ton tonluk',
          image_url:
            'https://gettransport.com/uploads/store/dd731919737daf5a122429d73319e75b.png'
        },
        {
          id: 10,
          title_en_us: '10-ton truck',
          position: 6,
          enabled: true,
          title_ru_ru: '10-тонный грузовик',
          title_de_de: '10-Tonnen',
          title_fr_fr: 'Camion de 10 tonnes',
          title_it_it: 'Camion da 10 tonnellate',
          title_es_es: 'Camión de 10 toneladas',
          title_pt_pt: '10 toneladas',
          title_nl_nl: 'Vrachtwagen van 10 ton',
          title_zh_cn: '10吨卡车',
          title_el_gr: '10-τόνος',
          title_hi_in: '10 टन ट्रक',
          title_tr_tr: '10 ton tonluk',
          image_url:
            'https://gettransport.com/uploads/store/586044009a430c3ae8d330db6fe6d618.png'
        },
        {
          id: 6,
          title_en_us: '20-ton truck',
          position: 7,
          enabled: true,
          title_ru_ru: '20-тонный грузовик',
          title_de_de: '20-Tonnen',
          title_fr_fr: 'Camion de 20 tonnes',
          title_it_it: 'Camion da 20 tonnellate',
          title_es_es: 'Camión de 20 toneladas',
          title_pt_pt: '20 toneladas',
          title_nl_nl: 'Vrachtwagen van 20 ton',
          title_zh_cn: '20吨卡车',
          title_el_gr: '20-τόνος',
          title_hi_in: '20 टन ट्रक',
          title_tr_tr: '20 ton tonluk',
          image_url:
            'https://gettransport.com/uploads/store/369639001d1f33d7e6a12370cf15cbc5.png'
        },
        {
          id: 7,
          title_en_us: 'Hauler',
          position: 8,
          enabled: false,
          title_ru_ru: 'Тягач',
          title_de_de: 'Schlepper',
          title_fr_fr: 'Tombereau',
          title_it_it: 'Bisarca',
          title_es_es: 'Сamión remolque',
          title_pt_pt: 'Caminhao',
          title_nl_nl: 'Vervoerder',
          title_zh_cn: '搬运工',
          title_el_gr: 'Μεταφορέας',
          title_hi_in: 'होलियर',
          title_tr_tr: 'Hauler',
          image_url:
            'https://gettransport.com/uploads/store/3fd7d21d4a3ac11d1d0a2120a0a73259.png'
        },
        {
          id: 8,
          title_en_us: 'Container',
          position: 9,
          enabled: true,
          title_ru_ru: 'Контейнер',
          title_de_de: 'Container',
          title_fr_fr: 'Conteneur',
          title_it_it: 'Сontainer',
          title_es_es: 'Contenedor',
          title_pt_pt: 'Recipiente',
          title_nl_nl: 'Container',
          title_zh_cn: '容器',
          title_el_gr: 'Δοχείο',
          title_hi_in: 'कंटेनर',
          title_tr_tr: 'Konteyner',
          image_url:
            'https://gettransport.com/uploads/store/56c3351cd197320095e8cf3c64040995.png'
        },
        {
          id: 9,
          title_en_us: 'Carrier',
          position: 10,
          enabled: true,
          title_ru_ru: 'Автовоз',
          title_de_de: 'Träger',
          title_fr_fr: 'Transporteur',
          title_it_it: 'Bisarca',
          title_es_es: 'Portador',
          title_pt_pt: 'Transportador',
          title_nl_nl: 'Vervoerder',
          title_zh_cn: '承运人',
          title_el_gr: 'Μεταφορέας',
          title_hi_in: 'कैरियर',
          title_tr_tr: 'Taşımacı',
          image_url:
            'https://gettransport.com/uploads/store/993906d4fd7cae5217d8743503d7bb18.png'
        },
        {
          id: 12,
          title_en_us: 'Boat carrier',
          position: 11,
          enabled: true,
          title_ru_ru: 'Трал',
          title_de_de: 'Bootsträger',
          title_fr_fr: 'Transporteur de bateau',
          title_it_it: 'Nave portacontainer',
          title_es_es: 'Transporte de barcos',
          title_pt_pt: 'Navio de transporte de embarcações',
          title_nl_nl: 'Bootschip',
          title_zh_cn: '船载体',
          title_el_gr: 'Μεταφορέας σκαφών',
          title_hi_in: 'नाव वाहक',
          title_tr_tr: 'Tekne taşıyıcı',
          image_url:
            'https://gettransport.com/uploads/store/72088ba941f030d074d00e685db1b897.png'
        },
        {
          id: 11,
          title_en_us: 'Tipper',
          position: 12,
          enabled: true,
          title_ru_ru: 'Самосвал',
          title_de_de: 'Kipper',
          title_fr_fr: 'Benne',
          title_it_it: 'Autoribaltabile',
          title_es_es: 'Volquete',
          title_pt_pt: 'Tipper',
          title_nl_nl: 'Kipper',
          title_zh_cn: '小费',
          title_el_gr: 'Ανατροπή',
          title_hi_in: 'टिपर',
          title_tr_tr: 'Damperli',
          image_url:
            'https://gettransport.com/uploads/store/f7c83d9535ba976b3a93530d6315524d.png'
        },
        {
          id: 13,
          title_en_us: 'Tank truck',
          position: 13,
          enabled: true,
          title_ru_ru: 'Автоцистерна',
          title_de_de: 'Tankwagen',
          title_fr_fr: 'Camion de réservoir de',
          title_it_it: 'Camion cisterna',
          title_es_es: 'Camión cisterna',
          title_pt_pt: 'Camião-cisterna',
          title_nl_nl: 'Tankwagen',
          title_zh_cn: '油罐车',
          title_el_gr: 'Φορτηγό δεξαμενών',
          title_hi_in: 'टैंक ट्रक',
          title_tr_tr: 'Tank kam truckyonu',
          image_url:
            'https://gettransport.com/uploads/store/ebc2f89cba7d6d58660f4375a3e6f041.png'
        }
      ],
      currencies: [
        {
          id: 12,
          code: 'CNY',
          name_en_us: 'Yuan',
          name_ru_ru: 'Юань',
          main: true,
          name_de_de: 'Yuan',
          name_fr_fr: 'Yuan',
          name_it_it: 'Yuan',
          name_es_es: 'Yuan',
          name_pt_pt: 'Yuan',
          name_nl_nl: 'Yuan',
          name_zh_cn: '元',
          name_el_gr: 'Γιουάν',
          name_hi_in: 'युआन',
          name_tr_tr: 'Yuan'
        },
        {
          id: 2,
          code: 'EUR',
          name_en_us: 'Euro',
          name_ru_ru: 'Евро',
          main: true,
          name_de_de: 'Euro',
          name_fr_fr: 'Euro',
          name_it_it: 'Euro',
          name_es_es: 'Euro',
          name_pt_pt: 'Euro',
          name_nl_nl: 'Euro',
          name_zh_cn: '欧元',
          name_el_gr: 'Ευρώ',
          name_hi_in: 'यूरो',
          name_tr_tr: 'Avro'
        },
        {
          id: 39,
          code: 'GBP',
          name_en_us: 'Pound sterling',
          name_ru_ru: 'Фунт стерлингов',
          main: true,
          name_de_de: 'Pfund sterling',
          name_fr_fr: 'La livre sterling',
          name_it_it: 'Sterlina inglese',
          name_es_es: 'Libra esterlina',
          name_pt_pt: 'Libra esterlina',
          name_nl_nl: 'Pond sterling',
          name_zh_cn: '英镑',
          name_el_gr: 'Στερλίνα',
          name_hi_in: 'पौंड स्टर्लिंग',
          name_tr_tr: 'İngiliz sterlini'
        },
        {
          id: 3,
          code: 'RUB',
          name_en_us: 'Russian ruble',
          name_ru_ru: 'Российский рубль',
          main: true,
          name_de_de: 'Russischer Rubel',
          name_fr_fr: 'Rouble russe',
          name_it_it: 'Rublo',
          name_es_es: 'Rublo ruso',
          name_pt_pt: 'Rublo russo',
          name_nl_nl: 'Russische Roebel',
          name_zh_cn: '俄罗斯卢布',
          name_el_gr: 'Ρούβλι',
          name_hi_in: 'रूसी रूबल',
          name_tr_tr: 'Rus rublesi'
        },
        {
          id: 1,
          code: 'USD',
          name_en_us: 'United States dollar',
          name_ru_ru: 'Доллар США',
          main: true,
          name_de_de: 'Us-dollar',
          name_fr_fr: 'Dollar des États-Unis',
          name_it_it: 'Dollaro degli Stati Uniti',
          name_es_es: 'Dólar de los Estados Unidos',
          name_pt_pt: 'Dólar dos Estados Unidos',
          name_nl_nl: 'Verenigde Staten dollar',
          name_zh_cn: '美元',
          name_el_gr: 'Δολάριο ΗΠΑ',
          name_hi_in: 'संयुक्त राज्य अमेरिका डॉलर',
          name_tr_tr: 'Amerika Birleşik Devletleri doları'
        },
        {
          id: 49,
          code: 'AED',
          name_en_us: 'United Arab Emirates dirham',
          name_ru_ru: 'Дирхам ОАЭ',
          main: false,
          name_de_de: 'Vereinigte Arabische Emirate dirham',
          name_fr_fr: 'Émirats Arabes Unis dirham',
          name_it_it: 'Dirham Degli Emirati Arabi Uniti',
          name_es_es: 'Emiratos Árabes Unidos dirham',
          name_pt_pt: 'Dirham dos Emirados Árabes Unidos',
          name_nl_nl: 'Verenigde Arabische Emiraten dirham',
          name_zh_cn: '阿拉伯联合Emirates长国迪拉姆',
          name_el_gr: 'Ηνωμένα Αραβικά Εμιράτα ντιρχάμ',
          name_hi_in: 'संयुक्त अरब अमीरात दिरहम',
          name_tr_tr: 'Birleşik Arap Emirlikleri dirhemi'
        },
        {
          id: 4,
          code: 'ARS',
          name_en_us: 'Argentine peso',
          name_ru_ru: 'Аргентинское песо',
          main: false,
          name_de_de: 'Argentinischer peso',
          name_fr_fr: 'Peso argentin',
          name_it_it: 'Peso Argentino',
          name_es_es: 'Peso argentino',
          name_pt_pt: 'Peso argentino',
          name_nl_nl: 'Argentijnse peso',
          name_zh_cn: '阿根廷比索',
          name_el_gr: 'Πέσο Αργεντινής',
          name_hi_in: 'अर्जेंटीना पेसो',
          name_tr_tr: 'Arjantin pezosu'
        },
        {
          id: 5,
          code: 'AUD',
          name_en_us: 'Australian dollar',
          name_ru_ru: 'Австралийский доллар',
          main: false,
          name_de_de: 'Australischer dollar',
          name_fr_fr: 'Dollar australien',
          name_it_it: 'Dollaro Australiano',
          name_es_es: 'Dólar australiano',
          name_pt_pt: 'Dólar australiano',
          name_nl_nl: 'Australische dollar',
          name_zh_cn: '澳元',
          name_el_gr: 'Δολάριο Αυστραλίας',
          name_hi_in: 'ऑस्ट्रेलियाई डॉलर',
          name_tr_tr: 'Avustralya Doları'
        },
        {
          id: 6,
          code: 'AZN',
          name_en_us: 'Azerbaijani manat',
          name_ru_ru: 'Азербайджанский манат',
          main: false,
          name_de_de: 'Aserbaidschanische manat',
          name_fr_fr: 'Manat azerbaïdjanais',
          name_it_it: 'Manat azero',
          name_es_es: 'Azerbaiyán manat',
          name_pt_pt: 'Manat do Azerbaijão',
          name_nl_nl: 'Azerbeidzjaans manaat',
          name_zh_cn: '阿塞拜疆马纳特',
          name_el_gr: 'Μανάτ του Αζερμπαϊτζάν',
          name_hi_in: 'अज़रबैजानी manat',
          name_tr_tr: 'Azerbaycan manatı'
        },
        {
          id: 9,
          code: 'BGN',
          name_en_us: 'Bulgarian lev',
          name_ru_ru: 'Болгарский лев',
          main: false,
          name_de_de: 'Bulgarische Lew',
          name_fr_fr: 'Nouveau lev bulgare',
          name_it_it: 'Lev Bulgaro',
          name_es_es: 'Lev búlgaro',
          name_pt_pt: 'Lev búlgaro',
          name_nl_nl: 'Bulgaarse lev',
          name_zh_cn: '保加利亚列弗',
          name_el_gr: 'Βουλγαρικό Λεβ',
          name_hi_in: 'बुल्गारियाई लेव',
          name_tr_tr: 'Bulgar lev'
        },
        {
          id: 7,
          code: 'BHD',
          name_en_us: 'Bahraini dinar',
          name_ru_ru: 'Бахрейнский динар',
          main: false,
          name_de_de: 'Bahrain-dinar',
          name_fr_fr: 'Dinar de bahreïn',
          name_it_it: 'Dinaro del Bahrain',
          name_es_es: 'Dinar bahreiní',
          name_pt_pt: 'Dinar do Bahraini',
          name_nl_nl: 'Bahraini dinar',
          name_zh_cn: '巴林第纳尔',
          name_el_gr: 'Δηνάριο Μπαχρέιν',
          name_hi_in: 'बहरीन दिनार',
          name_tr_tr: 'Bahreyn dinarı'
        },
        {
          id: 8,
          code: 'BRL',
          name_en_us: 'Brazilian real',
          name_ru_ru: 'Бразильский реал',
          main: false,
          name_de_de: 'Brasilianischer real',
          name_fr_fr: 'Brazilian real',
          name_it_it: 'Brasiliano reale',
          name_es_es: 'Real brasileño',
          name_pt_pt: 'Real brasileiro',
          name_nl_nl: 'Braziliaanse real',
          name_zh_cn: '巴西雷亚尔',
          name_el_gr: 'Βραζιλίας πραγματικό',
          name_hi_in: 'ब्राजील असली',
          name_tr_tr: 'Brezilya Reali'
        },
        {
          id: 46,
          code: 'CHF',
          name_en_us: 'Swiss franc',
          name_ru_ru: 'Швейцарский франк',
          main: false,
          name_de_de: 'Schweizerfranken',
          name_fr_fr: 'Franc suisse',
          name_it_it: 'Franco Svizzero',
          name_es_es: 'Franco suizo',
          name_pt_pt: 'Franco suíço',
          name_nl_nl: 'Zwitserse Frank',
          name_zh_cn: '瑞士法郎',
          name_el_gr: 'Ελβετικό φράγκο',
          name_hi_in: 'स्विस फ्रैंक',
          name_tr_tr: 'İsviçre Frangı'
        },
        {
          id: 11,
          code: 'CLP',
          name_en_us: 'Chilean peso',
          name_ru_ru: 'Чилийское песо',
          main: false,
          name_de_de: 'Westafrikanischer Cfa-franc',
          name_fr_fr: 'Peso chilien',
          name_it_it: 'Cileno',
          name_es_es: 'Peso chileno',
          name_pt_pt: 'Peso chileno',
          name_nl_nl: 'Chileense peso',
          name_zh_cn: '智利比索',
          name_el_gr: 'Πέσο Χιλής',
          name_hi_in: 'चिली पेसो',
          name_tr_tr: 'Şili pezosu'
        },
        {
          id: 13,
          code: 'COP',
          name_en_us: 'Colombian peso',
          name_ru_ru: 'Колумбийское песо',
          main: false,
          name_de_de: 'Kolumbianischen peso',
          name_fr_fr: 'Peso colombien',
          name_it_it: 'Peso Colombiano',
          name_es_es: 'Peso colombiano',
          name_pt_pt: 'Peso colombiano',
          name_nl_nl: 'Colombiaanse peso',
          name_zh_cn: '哥伦比亚比索',
          name_el_gr: 'Πέσο Κολομβίας',
          name_hi_in: 'कोलम्बियाई पीसो',
          name_tr_tr: 'Kolombiya pezosu'
        },
        {
          id: 14,
          code: 'CZK',
          name_en_us: 'Czech koruna',
          name_ru_ru: 'Чешская крона',
          main: false,
          name_de_de: 'Tschechische Krone',
          name_fr_fr: 'Couronne tchèque',
          name_it_it: 'Corona Ceca',
          name_es_es: 'Checo koruna',
          name_pt_pt: 'Coroa Checa',
          name_nl_nl: 'Tsjechische kroon',
          name_zh_cn: '捷克克朗',
          name_el_gr: 'Κορόνα Τσεχίας',
          name_hi_in: 'चेक कोरुना',
          name_tr_tr: 'Çek korunası'
        },
        {
          id: 15,
          code: 'DKK',
          name_en_us: 'Danish krone',
          name_ru_ru: 'Датская крона',
          main: false,
          name_de_de: 'Dänische krone',
          name_fr_fr: 'Danoise',
          name_it_it: 'Corona Danese',
          name_es_es: 'Corona danesa',
          name_pt_pt: 'Dinamarquês',
          name_nl_nl: 'Deense Kroon',
          name_zh_cn: '丹麦克朗',
          name_el_gr: 'Δανική κορόνα',
          name_hi_in: 'डैनिश क्रोन',
          name_tr_tr: 'Danimarka Kronu'
        },
        {
          id: 16,
          code: 'EGP',
          name_en_us: 'Egyptian pound',
          name_ru_ru: 'Египетский фунт',
          main: false,
          name_de_de: 'Ägyptisches Pfund',
          name_fr_fr: 'Livre égyptienne',
          name_it_it: 'Sterlina Egiziana',
          name_es_es: 'Libra egipcia',
          name_pt_pt: 'Libra egípcia',
          name_nl_nl: 'Egyptisch pond',
          name_zh_cn: '埃及镑',
          name_el_gr: 'Αιγυπτιακή Λίρα',
          name_hi_in: 'मिस्र पाउण्ड',
          name_tr_tr: 'Mısır pound'
        },
        {
          id: 18,
          code: 'FJD',
          name_en_us: 'Fijian dollar',
          name_ru_ru: 'Доллар Фиджи',
          main: false,
          name_de_de: 'Fidschi-dollar',
          name_fr_fr: 'Dollar fidjien',
          name_it_it: 'Dollaro Delle Fiji',
          name_es_es: 'Dólar fiyiano',
          name_pt_pt: 'Dólar de Fiji',
          name_nl_nl: 'Fijiaanse dollar',
          name_zh_cn: '斐济元',
          name_el_gr: 'Δολάριο των Φίτζι',
          name_hi_in: 'फ़ीजी डालर',
          name_tr_tr: 'Fiji doları'
        },
        {
          id: 19,
          code: 'GEL',
          name_en_us: 'Georgian lari',
          name_ru_ru: 'Грузинский лари',
          main: false,
          name_de_de: 'Georgische lari',
          name_fr_fr: 'Lari géorgien',
          name_it_it: 'Lari Georgiano',
          name_es_es: 'Lari georgiano',
          name_pt_pt: 'Lari Georgiano',
          name_nl_nl: 'Georgische lari',
          name_zh_cn: '格鲁吉亚拉里',
          name_el_gr: 'Γεωργιανό Λάρι',
          name_hi_in: 'जॉर्जियाई lari',
          name_tr_tr: 'Gürcü lari'
        },
        {
          id: 20,
          code: 'HKD',
          name_en_us: 'Hong Kong dollar',
          name_ru_ru: 'Гонконгский доллар',
          main: false,
          name_de_de: 'Hongkong dollar',
          name_fr_fr: 'Dollar De Hong Kong',
          name_it_it: 'Dollaro Di Hong Kong',
          name_es_es: 'Dólar de Hong Kong',
          name_pt_pt: 'Dólar de Hong Kong',
          name_nl_nl: 'Hongkong dollar',
          name_zh_cn: '港币',
          name_el_gr: 'Δολάριο Χονγκ Κονγκ',
          name_hi_in: 'हांगकांग डालर',
          name_tr_tr: 'Hong Kong doları'
        },
        {
          id: 21,
          code: 'HUF',
          name_en_us: 'Hungarian forint',
          name_ru_ru: 'Форинт',
          main: false,
          name_de_de: 'Ungarischer forint',
          name_fr_fr: 'Forint hongrois',
          name_it_it: 'Fiorino Ungherese',
          name_es_es: 'Forint húngaro',
          name_pt_pt: 'Forint húngaro',
          name_nl_nl: 'Hongaarse forint',
          name_zh_cn: '匈牙利福林',
          name_el_gr: 'Ουγγρικό φιορίνι',
          name_hi_in: 'हंगरी फ़ोरिंट',
          name_tr_tr: 'Macar forint'
        },
        {
          id: 23,
          code: 'IDR',
          name_en_us: 'Indonesian rupiah',
          name_ru_ru: 'Индонезийская рупия',
          main: false,
          name_de_de: 'Indonesische rupiah',
          name_fr_fr: 'Roupie indonésienne',
          name_it_it: 'Rupia Indonesiana',
          name_es_es: 'Rupia indonesia',
          name_pt_pt: 'Rupia indonésia',
          name_nl_nl: 'Indonesische rupiah',
          name_zh_cn: '印尼盾',
          name_el_gr: 'Ινδονησιακή ρουπία',
          name_hi_in: 'इंडोनेशियाई रुपिया',
          name_tr_tr: 'Endonezya rupiah'
        },
        {
          id: 33,
          code: 'ILS',
          name_en_us: 'Israeli new shekel',
          name_ru_ru: 'Новый израильский шекель',
          main: false,
          name_de_de: 'Israelischer neuer Schekel',
          name_fr_fr: 'Nouveaux shekels israéliens',
          name_it_it: 'Nuovo Siclo Israeliano',
          name_es_es: 'Nuevo shekel israelí',
          name_pt_pt: 'Shekel novo israelita',
          name_nl_nl: 'Israëlische Nieuwe shekel',
          name_zh_cn: '以色列新谢克尔',
          name_el_gr: 'Ισραηλινό Νέο Σέκελ',
          name_hi_in: 'इजरायल की नई शेकेल',
          name_tr_tr: 'İsrail yeni şekel'
        },
        {
          id: 22,
          code: 'INR',
          name_en_us: 'Indian rupee',
          name_ru_ru: 'Индийская рупия',
          main: false,
          name_de_de: 'Indische Rupie',
          name_fr_fr: 'Roupie indienne',
          name_it_it: 'Rupia Indiana',
          name_es_es: 'Rupia india',
          name_pt_pt: 'Rupia indiana',
          name_nl_nl: 'Indische roepie',
          name_zh_cn: '印度卢比',
          name_el_gr: 'Ινδική ρουπία',
          name_hi_in: 'भारतीय रुपया',
          name_tr_tr: 'Hint rupisi'
        },
        {
          id: 25,
          code: 'JOD',
          name_en_us: 'Jordanian dinar',
          name_ru_ru: 'Иорданский динар',
          main: false,
          name_de_de: 'Jordanischer dinar',
          name_fr_fr: 'Dinar jordanien',
          name_it_it: 'Dinaro Giordano',
          name_es_es: 'Dinar jordano',
          name_pt_pt: 'Dinar jordano',
          name_nl_nl: 'Jordaanse dinar',
          name_zh_cn: '约旦第纳尔',
          name_el_gr: 'Δηνάριο Ιορδανίας',
          name_hi_in: 'जॉर्डनियाई दीनार',
          name_tr_tr: 'Ürdün dinarı'
        },
        {
          id: 24,
          code: 'JPY',
          name_en_us: 'Japanese yen',
          name_ru_ru: 'Иена',
          main: false,
          name_de_de: 'Japanischer yen',
          name_fr_fr: 'Yen japonais',
          name_it_it: 'Yen Giapponese',
          name_es_es: 'Yenes japoneses',
          name_pt_pt: 'Yen japonês',
          name_nl_nl: 'Japanse yen',
          name_zh_cn: '日元',
          name_el_gr: 'Γεν',
          name_hi_in: 'जापानी येन',
          name_tr_tr: 'Japon Yeni'
        },
        {
          id: 27,
          code: 'KRW',
          name_en_us: 'South Korean won',
          name_ru_ru: 'Южнокорейская вона',
          main: false,
          name_de_de: 'Südkoreaner gewonnen',
          name_fr_fr: 'Won sud-coréen',
          name_it_it: 'Won Sudcoreano',
          name_es_es: 'Corea del Sur ganó',
          name_pt_pt: 'Won da Coreia do Sul',
          name_nl_nl: 'Zuid-Koreaanse won',
          name_zh_cn: '韩元',
          name_el_gr: 'Νότια Κορέα κέρδισε',
          name_hi_in: 'दक्षिण कोरियाई वोन',
          name_tr_tr: 'Güney Kore kazandı'
        },
        {
          id: 28,
          code: 'KWD',
          name_en_us: 'Kuwaiti dinar',
          name_ru_ru: 'Кувейтский динар',
          main: false,
          name_de_de: 'Kuwaitischer dinar',
          name_fr_fr: 'Dinar koweïtien',
          name_it_it: 'Dinaro Kuwaitiano',
          name_es_es: 'Dinar kuwaití',
          name_pt_pt: 'Dinar kuwaitiano',
          name_nl_nl: 'Koeweitse dinar',
          name_zh_cn: '科威特第纳尔',
          name_el_gr: 'Δηνάριο του Κουβέιτ',
          name_hi_in: 'कुवैती दिनार',
          name_tr_tr: 'Kuveyt dinarı'
        },
        {
          id: 26,
          code: 'KZT',
          name_en_us: 'Kazakhstani tenge',
          name_ru_ru: 'Казахстанский тенге',
          main: false,
          name_de_de: 'Kasachischer tenge',
          name_fr_fr: 'Tenge kazakh',
          name_it_it: 'Tenge Kazakhstani',
          name_es_es: 'Tenge kazajstán',
          name_pt_pt: 'Tenge do Cazaquistão',
          name_nl_nl: 'Kazachstaanse tenge',
          name_zh_cn: '哈萨克斯坦坚戈',
          name_el_gr: 'Καζακστάν tenge',
          name_hi_in: 'Kazakhstani tenge',
          name_tr_tr: 'Kazakistan tenge'
        },
        {
          id: 31,
          code: 'MDL',
          name_en_us: 'Moldovan leu',
          name_ru_ru: 'Молдавский лей',
          main: false,
          name_de_de: 'Moldovan leu',
          name_fr_fr: 'Leu Moldave',
          name_it_it: 'Leu Moldavo',
          name_es_es: 'Moldavo leu',
          name_pt_pt: 'Leu da Moldávia',
          name_nl_nl: 'Moldavische leu',
          name_zh_cn: '摩尔多瓦列伊',
          name_el_gr: 'Μολδαβική λέου',
          name_hi_in: 'Moldovan लियू',
          name_tr_tr: 'Moldovalı leu'
        },
        {
          id: 30,
          code: 'MXN',
          name_en_us: 'Mexican peso',
          name_ru_ru: 'Мексиканское песо',
          main: false,
          name_de_de: 'Mexikanischer peso',
          name_fr_fr: 'Peso mexicain',
          name_it_it: 'Peso Messicano',
          name_es_es: 'Peso mexicano',
          name_pt_pt: 'Peso mexicano',
          name_nl_nl: 'Mexicaanse peso',
          name_zh_cn: '墨西哥比索',
          name_el_gr: 'Πέσο Μεξικού',
          name_hi_in: 'मेक्सिकन पीसो',
          name_tr_tr: 'Meksika pezosu'
        },
        {
          id: 29,
          code: 'MYR',
          name_en_us: 'Malaysian ringgit',
          name_ru_ru: 'Малайзийский ринггит',
          main: false,
          name_de_de: 'Malaysischer ringgit',
          name_fr_fr: 'Ringgit de malaisie',
          name_it_it: 'Ringgit malese',
          name_es_es: 'Ringgit malasio',
          name_pt_pt: 'Ringgit da Malásia',
          name_nl_nl: 'Maleisische ringgit',
          name_zh_cn: '马来西亚令吉',
          name_el_gr: 'Μαλαισιανό ρίνγκιτ',
          name_hi_in: 'मलेशियाई रिंगित',
          name_tr_tr: 'Malezya ringgit'
        },
        {
          id: 32,
          code: 'NAD',
          name_en_us: 'Namibian dollar',
          name_ru_ru: 'Доллар Намибии',
          main: false,
          name_de_de: 'Namibia dollar',
          name_fr_fr: 'Dollar namibien',
          name_it_it: 'Dollaro della Namibia',
          name_es_es: 'Dólar de Namibia',
          name_pt_pt: 'Dólar namibiano',
          name_nl_nl: 'Namibië-dollar',
          name_zh_cn: '斐济元',
          name_el_gr: 'Δολάριο της Ναμίμπια',
          name_hi_in: 'नामीबिया डॉलर',
          name_tr_tr: 'Namibya doları'
        },
        {
          id: 36,
          code: 'NOK',
          name_en_us: 'Norwegian krone',
          name_ru_ru: 'Норвежская крона',
          main: false,
          name_de_de: 'Norwegische krone',
          name_fr_fr: 'Norvégienne',
          name_it_it: 'Corona Norvegese',
          name_es_es: 'Corona noruega',
          name_pt_pt: 'Coroa Norueguesa',
          name_nl_nl: 'Noorse Kroon',
          name_zh_cn: '挪威克朗',
          name_el_gr: 'Νορβηγική κορόνα',
          name_hi_in: 'नॉर्वे क्रोन',
          name_tr_tr: 'Norveç Kronu'
        },
        {
          id: 35,
          code: 'NZD',
          name_en_us: 'New Zealand dollar',
          name_ru_ru: 'Новозеландский доллар',
          main: false,
          name_de_de: 'Neuseeland-dollar',
          name_fr_fr: 'Dollar néo-zélandais',
          name_it_it: 'Dollaro della Nuova Zelanda',
          name_es_es: 'Dólar neozelandés',
          name_pt_pt: 'Dólar da Nova Zelândia',
          name_nl_nl: 'Nieuwzeelandse dollar',
          name_zh_cn: '新西兰元',
          name_el_gr: 'Δολάριο Νέας Ζηλανδίας',
          name_hi_in: 'न्यूजीलैंड डालर',
          name_tr_tr: 'Yeni Zelanda doları'
        },
        {
          id: 37,
          code: 'OMR',
          name_en_us: 'Omani rial',
          name_ru_ru: 'Оманский риал',
          main: false,
          name_de_de: 'Oman-rial',
          name_fr_fr: 'Omani rial',
          name_it_it: "Rial dell'Oman",
          name_es_es: 'Rial omaní',
          name_pt_pt: 'Rial Omani',
          name_nl_nl: 'Omani rial',
          name_zh_cn: '阿曼里亚尔',
          name_el_gr: 'Ομάν Ριάλ',
          name_hi_in: 'ओमानी रियाल',
          name_tr_tr: 'Umman riyali'
        },
        {
          id: 38,
          code: 'PLN',
          name_en_us: 'Polish złoty',
          name_ru_ru: 'Польский злотый',
          main: false,
          name_de_de: 'Polnischer złoty',
          name_fr_fr: 'Zloty polonais',
          name_it_it: 'Złoty polacco',
          name_es_es: 'Zloty polaco',
          name_pt_pt: 'Zloti polaco',
          name_nl_nl: 'Pools złoty',
          name_zh_cn: '波兰语złoty',
          name_el_gr: 'Πολωνικό ζλότι',
          name_hi_in: 'पोलिश नंगा',
          name_tr_tr: 'Polonya zlotisi'
        },
        {
          id: 40,
          code: 'QAR',
          name_en_us: 'Qatari riyal',
          name_ru_ru: 'Катарский риал',
          main: false,
          name_de_de: 'Katar-riyal',
          name_fr_fr: 'Qatari riyal',
          name_it_it: 'Qatar riyal',
          name_es_es: 'Riyal qatarí',
          name_pt_pt: 'Riyal Qatari',
          name_nl_nl: 'Qatari riyal',
          name_zh_cn: '卡塔尔里亚尔',
          name_el_gr: 'Κατάρ Ριάλ',
          name_hi_in: 'क़तर रियाल',
          name_tr_tr: 'Katar riyali'
        },
        {
          id: 41,
          code: 'RON',
          name_en_us: 'Romanian leu',
          name_ru_ru: 'Румынский лей',
          main: false,
          name_de_de: 'Rumänischer leu',
          name_fr_fr: 'Leu Roumain',
          name_it_it: 'Leu rumeno',
          name_es_es: 'Leu rumano',
          name_pt_pt: 'Leu romeno',
          name_nl_nl: 'Roemeense leu',
          name_zh_cn: '罗马尼亚列伊',
          name_el_gr: 'Ρουμανικό λέου',
          name_hi_in: 'रोमानियाई लियू',
          name_tr_tr: 'Romen leu'
        },
        {
          id: 43,
          code: 'SAR',
          name_en_us: 'Saudi riyal',
          name_ru_ru: 'Саудовский риял',
          main: false,
          name_de_de: 'Saudi-Rial',
          name_fr_fr: 'Saoudite riyal',
          name_it_it: 'Riyal Saudita',
          name_es_es: 'Riyal saudí',
          name_pt_pt: 'Rial Saudita',
          name_nl_nl: 'Saudi riyal',
          name_zh_cn: '沙特里亚尔',
          name_el_gr: 'Σαουδική Ριάλ',
          name_hi_in: 'सउदी रियाल',
          name_tr_tr: 'Suudi riyali'
        },
        {
          id: 44,
          code: 'SGD',
          name_en_us: 'Singapore dollar',
          name_ru_ru: 'Сингапурский доллар',
          main: false,
          name_de_de: 'Singapur-dollar',
          name_fr_fr: 'Dollar de singapour',
          name_it_it: 'Dollaro Di Singapore',
          name_es_es: 'Dólar de Singapur',
          name_pt_pt: 'Dólar de Singapura',
          name_nl_nl: 'Singapore-dollar',
          name_zh_cn: '新加坡元',
          name_el_gr: 'Δολάριο Σιγκαπούρης',
          name_hi_in: 'सिंगापुर डॉलर',
          name_tr_tr: 'Singapur doları'
        },
        {
          id: 47,
          code: 'THB',
          name_en_us: 'Thai baht',
          name_ru_ru: 'Тайский бат',
          main: false,
          name_de_de: 'Thai baht',
          name_fr_fr: 'Baht thaïlandais',
          name_it_it: 'Baht Thailandese',
          name_es_es: 'Baht tailandés',
          name_pt_pt: 'Baht Tailandês',
          name_nl_nl: 'Thaise baht',
          name_zh_cn: '泰铢',
          name_el_gr: 'Ταϊλανδικό μπατ',
          name_hi_in: 'थाई बात',
          name_tr_tr: 'Tayland Bahtı'
        },
        {
          id: 48,
          code: 'TRY',
          name_en_us: 'Turkish lira',
          name_ru_ru: 'Турецкая лира',
          main: false,
          name_de_de: 'Türkische lira',
          name_fr_fr: 'Livre turque',
          name_it_it: 'Lira Turca',
          name_es_es: 'Lira turca',
          name_pt_pt: 'Lira turca',
          name_nl_nl: 'Turkse lira',
          name_zh_cn: '土耳其里拉',
          name_el_gr: 'Τουρκική λίρα',
          name_hi_in: 'तुर्की लीरा',
          name_tr_tr: 'Türk Lirası'
        },
        {
          id: 34,
          code: 'TWD',
          name_en_us: 'New Taiwan dollar',
          name_ru_ru: 'Новый тайваньский доллар',
          main: false,
          name_de_de: 'Neue Taiwan-dollar',
          name_fr_fr: 'Nouveau Dollar De Taïwan',
          name_it_it: 'Nuovo Dollaro Di Taiwan',
          name_es_es: 'Nuevo dólar de Taiwán',
          name_pt_pt: 'Novo Dólar de Taiwan',
          name_nl_nl: 'Nieuwe Taiwanese dollar',
          name_zh_cn: '新台币',
          name_el_gr: 'Νέο δολάριο Ταϊβάν',
          name_hi_in: 'नई ताइवान डॉलर',
          name_tr_tr: 'Yeni Tayvan doları'
        },
        {
          id: 51,
          code: 'UAH',
          name_en_us: 'Ukrainian hryvnia',
          name_ru_ru: 'Украинская гривна',
          main: false,
          name_de_de: 'Ukrainische Griwna',
          name_fr_fr: 'Hryvnia ukrainien',
          name_it_it: 'Grivna ucraina',
          name_es_es: 'Hryvnia ucraniano',
          name_pt_pt: 'Hryvnia Ucraniana',
          name_nl_nl: 'Oekraïense hryvnia',
          name_zh_cn: '乌克兰格里夫纳',
          name_el_gr: 'Ουκρανικά εθνικού νομίσματος',
          name_hi_in: 'यूक्रेनी रिव्निया',
          name_tr_tr: 'Ukrayna grivnası'
        },
        {
          id: 10,
          code: 'XOF',
          name_en_us: 'West African CFA franc',
          name_ru_ru: 'Франк КФА BCEAO',
          main: false,
          name_de_de: 'Westafrikanischer CFA-franc',
          name_fr_fr: "Afrique de l'ouest du franc CFA",
          name_it_it: "Franco CFA dell'Africa occidentale",
          name_es_es: 'Franco CFA de África Occidental',
          name_pt_pt: 'Franco CFA da África Ocidental',
          name_nl_nl: 'West-Afrikaanse CFA-Frank',
          name_zh_cn: '西非非洲金融共同体法郎',
          name_el_gr: 'Φράγκο CFA της Δυτικής Αφρικής',
          name_hi_in: 'पश्चिम अफ्रीकी CFA फ्रैंक',
          name_tr_tr: 'Batı Afrika CFA Frangı'
        },
        {
          id: 45,
          code: 'ZAR',
          name_en_us: 'South African rand',
          name_ru_ru: 'Южноафриканский рэнд',
          main: false,
          name_de_de: 'Südafrikanischer rand',
          name_fr_fr: 'Rand Sud-Africain',
          name_it_it: 'Rand Sudafricano',
          name_es_es: 'Rand sudafricano',
          name_pt_pt: 'Rand da África do Sul',
          name_nl_nl: 'Zuid-Afrikaanse rand',
          name_zh_cn: '南非兰特',
          name_el_gr: 'Ραντ Νότιας Αφρικής',
          name_hi_in: 'दक्षिण अफ्रीकी रैंड',
          name_tr_tr: 'Güney Afrika rand'
        }
      ],
      languages: [
        { id: 1, lang_code: 'ru_ru', lang_name: 'Русский' },
        { id: 2, lang_code: 'en_us', lang_name: 'English' },
        { id: 3, lang_code: 'de_de', lang_name: 'Deutsch' },
        { id: 4, lang_code: 'fr_fr', lang_name: 'Français' },
        { id: 5, lang_code: 'it_it', lang_name: 'Italiano' },
        { id: 6, lang_code: 'es_es', lang_name: 'Español' },
        { id: 7, lang_code: 'pt_pt', lang_name: 'Português' },
        { id: 8, lang_code: 'nl_nl', lang_name: 'Nederlands' },
        { id: 9, lang_code: 'zh_cn', lang_name: '中文' },
        { id: 10, lang_code: 'el_gr', lang_name: 'Ελληνικά' },
        { id: 11, lang_code: 'hi_in', lang_name: 'हिन्दी' },
        { id: 12, lang_code: 'tr_tr', lang_name: 'Türkçe' }
      ]
    }
  },
  methods: {
    testFormChange() {}
  }
}
</script>
